stages:
  - stage: 'Build'
    displayName: 'Build'
    jobs:
      - job: PackageBuildArtifacts
        displayName: 'Package Build Artifacts'

        pool:
          vmImage: $(Build.AgentPoolVmImage)

        variables:
          - template: '../variables/build-variables.yml'

        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Install GitVersion'
            inputs:
              command: custom
              custom: tool
              arguments: 'update -g GitVersion.tool'

          - task: DotNetCoreCLI@2
            displayName: 'Run GitVersion'
            inputs:
              command: custom
              custom: gitversion
              arguments: '-nofetch -output buildserver'

          - task: CopyFiles@2
            displayName: 'Copy ARM Templates'
            inputs:
              SourceFolder: 'devops'
              Contents: '**/*json'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/arm-templates'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'artifacts'
              publishLocation: 'Container'
