parameters:
  stageName:
  stageDisplayName:
  dependsOn: ''
  condition: ''
  vmImage: 'ubuntu-latest'
  variablesTemplate: ''
  environmentGroup:

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageDisplayName }}
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}

  jobs:
  - deployment: 'DeployBuildArtifacts'
    displayName: 'Deploy Build Artifacts'

    pool:
      vmImage: ${{ parameters.vmImage }}

    variables:
    -  template: '${{ parameters.variablesTemplate }}'
    -  template: '../variables/common-variables.yml'

    environment: ${{ parameters.environmentGroup }}

    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPackage@1
            displayName: 'Download Package '
            inputs:
              feed: ''
              view: ''
              definition: ''
              version: ${{ parameters.AzModuleVersion }}
              downloadPath: '$(System.ArtifactsDirectory)/AzModule'

          - task: AzurePowerShell@5
            displayName: 'Run KeyVaultCollector'
            inputs:
              azureSubscription: ${{ variables['Release.AzConnection'] }}
              ScriptType: InlineScript
              Inline: |     
                 Import-Module -Name $(System.ArtifactsDirectory)/AzModule/KeyVaultCollector.psm1

                 $envToLower = '${{ parameters.stageDisplayName }}'.toLower()

                 $kvcItemsPath = "$(Pipeline.Workspace)/artifacts/arm-templates/secrets.$envToLower.json"

                 Register-AzResourceGroupSecrets -itemsJsonPath $kvcItemsPath -defaultResourceGroupName ${{ variables['Release.ResourceGroupName'] }} -defaultKeyVaultName ${{ variables['Release.KeyVaultName'] }}

              errorActionPreference: continue
              preferredAzurePowerShellVersion: '${{ variables.ModuleVersion}}'
              pwsh: true 